<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name = "EduMIP">
 <xacro:property name="wheel_sep" value="0.070" />
 <xacro:property name="wheel_radius" value="0.034" />
 <xacro:property name="wheel_width" value="0.010" />
 <xacro:property name="body_height" value="0.1" />
 <xacro:property name="body_width" value="0.050" />
 <xacro:property name="body_length" value="0.035" />
 <xacro:property name="camera_link" value="0.05" />
 <!-- Size of square 'camera' box -->

 <material name="body">
  <color rgba="0 0 0.8 1"/>
 </material>

 <material name="wheel">
  <color rgba="1 1 1 1"/>
 </material>

 <link name="edumip_body">
  <visual>
   <origin xyz="0 0 0"/>
   <geometry>
    <box size="${body_length} ${body_width} ${body_height}"/>
   </geometry>
   <material name="body"/>
  </visual>

  <collison>
   <origin xyz="0 0 0"/>
   <geometry>
    <box size="${body_length} ${body_width} ${body_height}"/>
   </geometry>
  </collison>

  <inertial>
    <origin xyz="0 0 -0.2"/>
    <mass value="1"/>
    <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
  </inertial>
 </link>

 <link name="wheelL">
  <visual>
   <origin rpy="1.57075 0 0" xyz="0 ${-wheel_width} 0"/>
   <material name="wheel"/>
   <geometry>
    <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
   </geometry>
  </visual>

  <collision>
   <origin rpy="1.57075 0 0" xyz="0 ${-wheel_width} 0"/>
   <geometry>
    <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
   </geometry>
  </collision>
  
  <inertial>
    <origin rpy="1.57075 0 0" xyz="0 ${-wheel_width} 0"/>
    <mass value="0.2"/>
    <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
  </inertial>
  
 </link>

  <link name="wheelR">
  <visual>
   <origin rpy="1.57075 0 0" xyz="0 ${wheel_width} 0"/>
   <material name="wheel"/>
   <geometry>
    <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
   </geometry>
  </visual>

    <collision>
   <origin rpy="1.57075 0 0" xyz="0 ${wheel_width} 0"/>
   <geometry>
    <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
   </geometry>
  </collision>
  
  <inertial>
    <origin rpy="1.57075 0 0" xyz="0 ${wheel_width} 0"/>
    <mass value="0.2"/>
    <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
  </inertial>
  </link>
  
  <link name="camera_link">
    <collision>
      <origin xyz="0 0 ${body_height}" rpy="0 0 0"/>
      <geometry>
    <box size="${camera_link} ${camera_link} ${camera_link}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${body_height}" rpy="0 0 0"/>
      <geometry>
    <box size="${camera_link} ${camera_link} ${camera_link}"/>
      </geometry>
      <material name="body"/>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 ${body_height}" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link> 

  <joint name="camera_joint" type="fixed">
    <axis xyz="0 1 0"/>
    <origin xyz="${camera_link} 0 ${body_height}"/>
    <parent link="edumip_body"/>
    <child link="camera_link"/>
  </joint>

<joint name="wheelL_joint" type="continuous">
 <parent link="edumip_body"/>
 <child link="wheelL"/>
 <axis xyz="0 1 0"/>
 <origin rpy="0 0 0" xyz="0 ${-body_width/2} ${-body_height/2}"/>
 <dynamics friction ="0.7"/>
</joint>

<joint name="wheelR_joint" type="continuous">
 <parent link="edumip_body"/>
 <child link="wheelR"/>
 <axis xyz="0 1 0"/>
 <origin rpy="0 0 0" xyz="0 ${body_width/2} ${-body_height/2}"/>
 <dynamics friction="0.7"/>
</joint>

 <gazebo reference="edumip_body">
   <material>Gazebo/Blue</material>
   <mu1>0.2</mu1>
   <mu2>0.2</mu2>    
 </gazebo>
 <gazebo reference="wheelR">
   <material>Gazebo/Green</material>
   <mu1>0.2</mu1>
   <mu2>0.2</mu2>    
 </gazebo>
 <gazebo reference="wheelL">
   <material>Gazebo/Red</material>
   <mu1>0.2</mu1>
   <mu2>0.2</mu2>    
 </gazebo>

 <gazebo>
 <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
   <legacyMode>false</legacyMode>
   <rosDebugLevel>3</rosDebugLevel>
   <alwaysOn>true</alwaysOn>
   <updateRate>10</updateRate>
   <leftJoint>wheelL_joint</leftJoint>
   <rightJoint>wheelR_joint</rightJoint>
   <wheelSeparation>${wheel_sep}</wheelSeparation>
   <wheelDiameter>${wheel_radius*2.0}</wheelDiameter>
   <torque>0.1</torque>
   <commandTopic>/edumip/cmd</commandTopic>
   <odometryTopic>/edumip/odom</odometryTopic>
   <odometryFrame>world</odometryFrame>
   <robotBaseFrame>edumip_body</robotBaseFrame>
   <publishTf>1</publishTf> 
   <publishWheelTF>false</publishWheelTF> 
   <publishWheelJointState>true</publishWheelJointState>  
   <wheelAcceleration>0</wheelAcceleration>
   <wheelTorque>0.1</wheelTorque>
   <odometrySource>world</odometrySource>
 </plugin>
</gazebo>

<gazebo reference="camera_link">
 <sensor type="camera" name="camera1">
   <update_rate>10.0</update_rate>
   <camera name="head">
     <horizontal_fov>1.3962634</horizontal_fov>
     <image>
       <width>800</width>
       <height>800</height>
       <format>R8G8B8</format>
     </image>
     <clip>
       <near>0.02</near>
       <far>300</far>
     </clip>
     <noise>
       <type>gaussian</type>
       <mean>0.0</mean>
       <stddev>0.007</stddev>
     </noise>
   </camera>
   <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
     <robotNamespace>edumip</robotNamespace>
     <alwaysOn>true</alwaysOn>
     <updateRate>30.0</updateRate>
     <cameraName>camera1</cameraName>
     <imageTopicName>image_raw</imageTopicName>
     <cameraInfoTopicName>camera_info</cameraInfoTopicName>
     <frameName>camera_link</frameName>
     <hackBaseline>0.07</hackBaseline>
     <distortionK1>0.0</distortionK1>
     <distortionK2>0.0</distortionK2>
     <distortionK3>0.0</distortionK3>
     <distortionT1>0.0</distortionT1>
     <distortionT2>0.0</distortionT2>
   </plugin>
 </sensor>
</gazebo>

</robot>


